//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sunshinedbEntities : DbContext
    {
        public sunshinedbEntities()
            : base("name=sunshinedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customer> customer { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<inventory> inventory { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<product> product { get; set; }
    }
}
