//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.inventory = new HashSet<inventory>();
            this.orders = new HashSet<orders>();
        }
    
        public string productID { get; set; }
        public string productName { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<inventory> inventory { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}
