//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string employeeID { get; set; }
        public string password { get; set; }
        public string department { get; set; }
    }
}
