//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public string inventoryID { get; set; }
        public string productID { get; set; }
        public int quantity { get; set; }
    
        public virtual product product { get; set; }
    }
}
