//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public string orderID { get; set; }
        public System.DateTime orderDate { get; set; }
        public System.DateTime requiredDate { get; set; }
        public string status { get; set; }
        public string customerID { get; set; }
        public string productID { get; set; }
        public int quantity { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
